# * ALEMBIC_INCLUDE_DIR
# * ALEMBIC_LIBRARY

find_path(ALEMBIC_INCLUDE_DIR
    NAMES
        "Alembic/Abc/All.h"
    PATHS
        "/usr/include"
        "/usr/local/include"
)
mark_as_advanced(ALEMBIC_INCLUDE_DIR)

find_file(ALEMBIC_LIBRARY libAlembic.a PATH_SUFFIXES lib/)
mark_as_advanced(ALEMBIC_LIBRARY)

find_file(HDF5_LIBRARY libhdf5.a PATH_SUFFIXES lib/)
mark_as_advanced(HDF5_LIBRARY)

find_file(SZIP_LIBRARY libszip.a PATH_SUFFIXES lib/)
mark_as_advanced(SZIP_LIBRARY)

find_file(ZLIB_LIBRARY libz.dylib PATH_SUFFIXES lib/)
mark_as_advanced(ZLIB_LIBRARY)

list(APPEND ALEMBIC_INCLUDE_DIRS ${ALEMBIC_INCLUDE_DIR})
list(APPEND ALEMBIC_INCLUDE_DIRS ${OPENEXR_INCLUDE_DIRS})

list(APPEND ALEMBIC_LIBRARIES ${ALEMBIC_LIBRARY})
list(APPEND ALEMBIC_LIBRARIES ${HDF5_LIBRARY})
list(APPEND ALEMBIC_LIBRARIES ${SZIP_LIBRARY})
list(APPEND ALEMBIC_LIBRARIES ${ZLIB_LIBRARY})
list(APPEND ALEMBIC_LIBRARIES ${OPENEXR_Half_LIBRARY})
list(APPEND ALEMBIC_LIBRARIES ${OPENEXR_Iex_LIBRARY})
list(APPEND ALEMBIC_LIBRARIES ${OPENEXR_IexMath_LIBRARY})
list(APPEND ALEMBIC_LIBRARIES ${OPENEXR_Imath_LIBRARY})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args("ALEMBIC"
    DEFAULT_MSG
    ALEMBIC_INCLUDE_DIR
	ALEMBIC_LIBRARY
)
